spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/catalog

server:
    port: 8082

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

queue:
  series:
    name: series-queue
  movie:
    name: movie-queue
