server:
  port: 8080
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      Instance:
        preferIpAddress: true
       
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: animal-service-route
          uri: lb://animal-service
          predicates:
            - Path=/animal/**
        - id: species-service-route
          uri: lb://species-service
          predicates:
            - Path=/species/**
