server:
  port: 8080
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
      Instance:
        preferIpAddress: true
       
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: series-service-route
          uri: lb://series-service
          predicates:
            - Path=/series/**
