spring:  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/digitalflix
    username: root
    password: rootroot
  
  rabbitmq:
    host: localhost
    username: guest
    password: guest

  sql:
    init:
      dataLocations: classPath:/movie_service.sql
      mode: always
  
  
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddlAuto: create-drop

server:
    port: 8081

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

queue:
  movie:
    name: movie-queue
