spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://mongodb:27017/series

server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

queue:
  series:
    name: series-queue
